[build]
  command = "jekyll build --source client"
  publish = "_site"

[build.environment]
  RUBY_VERSION   = "2.6.5"
  BUNDLER_FLAGS  = "--without=server"
  15SECONDLY_API = "https://fifteensecondly.herokuapp.com"

[[redirects]]
  from   = "favicon.ico"
  to     = "https://daily.co/favicon.ico"
  status = 200
